name: .NET 10 Preview C#14 CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET 10 Preview
      uses: actions/setup-dotnet@v10
      with:
        dotnet-version: '10.0.100-preview.2'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run
      run: dotnet run --configuration Release
